name: Pre-release Model

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*' # triggers on something like v1.0.0-pre-1

jobs:
  build-and-publish:
    name: Build and Create GitHub Pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code at the tagged commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[gdrive]"

      - name: Configure DVC remote
        run: |
          dvc remote modify gdrive_remote gdrive_service_account_json_file_path .dvc/gdrive_sa_credentials.json

      - name: Create service account file from secret
        env:
          GDRIVE_CREDS_JSON: ${{ secrets.GDRIVE_SA_JSON }}
        run: |
          python -c "import os; f = open('.dvc/gdrive_sa_credentials.json', 'w'); f.write(os.environ['GDRIVE_CREDS_JSON']); f.close()"

      - name: Pull data
        env:
          GDRIVE_ACKNOWLEDGE_ABUSE: "true"
        run: dvc pull

      - name: Run training pipeline
        run: |
          python pipeline/data_processing.py
          python pipeline/training.py

      - name: Create GitHub Pre-release with Model Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Pre-release Model ${{ github.ref_name }}
          body: "Automated pre-release of the ML model and vectorizer."
          prerelease: true
          files: |
            models/count_vectorizer.joblib
            models/naive_bayes.joblib