name: Release Model

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-release:
    name: Build and Create Stable Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code at tagged commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[gdrive]"

      - name: Configure DVC remote
        run: |
          dvc remote modify gdrive_remote gdrive_service_account_json_file_path .dvc/gdrive_sa_credentials.json

      - name: Create service account file from secret
        env:
          GDRIVE_CREDS_JSON: ${{ secrets.GDRIVE_SA_JSON }}
        run: |
          python -c "import os; f = open('.dvc/gdrive_sa_credentials.json', 'w'); f.write(os.environ['GDRIVE_CREDS_JSON']); f.close()"

      - name: Pull data
        env:
          GDRIVE_ACKNOWLEDGE_ABUSE: "true"
        run: dvc pull

      - name: Run preprocessing
        run: python pipeline/data_processing.py

      - name: Train model
        run: python pipeline/training.py

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release Model ${{ github.ref_name }}
          body: "Official release of the ML model and vectorizer."
          prerelease: false
          files: |
            models/count_vectorizer.joblib
            models/naive_bayes.joblib

  bump_version_on_main:
    name: Bump Version on Main Branch
    needs: build-and-release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Configure Git for bot user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Calculate next pre-release version
        run: |
          BASE_TAG=${{ github.ref_name }}
          BASE_VERSION=${BASE_TAG#v}
          IFS=. read -r MAJOR MINOR PATCH <<< "$BASE_VERSION"
          
          NEXT_PATCH=$((PATCH + 1))
          TIMESTAMP=$(date -u +%Y%m%d%H%M%S)
          NEXT_VERSION_STRING="v$MAJOR.$MINOR.$NEXT_PATCH-pre-$TIMESTAMP"
          
          echo "NEXT_VERSION=$NEXT_VERSION_STRING" >> $GITHUB_ENV

      - name: Update/Create version file in pipeline/__init__.py
        run: |
          # Define the path to the version file
          VERSION_FILE="pipeline/__init__.py"
          # Create the directory if it doesn't exist
          mkdir -p $(dirname ${VERSION_FILE})
          # Write the version string to the file
          echo "__version__ = \"${{ env.NEXT_VERSION }}\"" > ${VERSION_FILE}
          echo "Updated ${VERSION_FILE} on main branch to: ${{ env.NEXT_VERSION }}"
          cat ${VERSION_FILE}

      - name: Commit and push new version to main
        run: |
          # Use the same file path as the previous step
          VERSION_FILE="pipeline/__init__.py"
          git add ${VERSION_FILE}
          if git diff --staged --quiet; then
            echo "No version change to commit."
          else
            git commit -m "chore: Bump version to ${{ env.NEXT_VERSION }} for next dev cycle"
            git push origin main
          fi
      
