name: Release Model Training

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

env:
  PYTHON_VERSION: '3.10'

jobs:
  train-and-release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Parse version from tag
        run: |
          VERSION=${GITHUB_REF:11}
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Preprocess data
        run: python pipeline/data_processing.py

      - name: Train model
        run: python pipeline/training.py

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          generate_release_notes: true

      - name: Upload CountVectorizer model
        uses: svenstaro/upload-release-action@v2
        with:
          file: models/count_vectorizer.joblib
          asset_name: count_vectorizer-v${{ env.version }}.joblib
          tag: v${{ env.version }}

      - name: Upload Naive Bayes model
        uses: svenstaro/upload-release-action@v2
        with:
          file: models/naive_bayes.joblib
          asset_name: naive_bayes-v${{ env.version }}.joblib
          tag: v${{ env.version }}
