name: Release Model

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install DVC
        run: pip install 'dvc[gdrive]'

      # Directly write the secret content to a file
      - name: Create service account file from secret
        run: echo "${{ secrets.GDRIVE_SA_JSON }}" > gdrive_sa_credentials.json

      - name: Configure DVC remote
        run: |
          dvc remote modify gdrive_remote gdrive_service_account_json_file_path gdrive_sa_credentials.json

      - name: Pull data
        env:
          GDRIVE_ACKNOWLEDGE_ABUSE: "true"
        run: dvc pull

      - name: Run preprocessing
        run: python pipeline/data_processing.py

      - name: Train model
        run: python pipeline/training.py

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            models/count_vectorizer.joblib
            models/naive_bayes.joblib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}