name: Release Model

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install DVC
        run: pip install dvc[s3]

      - name: Pull data with DVC
        run: dvc pull

      - name: Run preprocessing
        run: python pipeline/data_processing.py

      - name: Train model
        run: python pipeline/training.py

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            models/count_vectorizer.joblib
            models/naive_bayes.joblib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
